---
# Copyright 2016 LSD/UFCG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create monasca-agent tarball
  command: "/opt/venvs/monasca-agent/bin/python setup.py sdist"
  args:
    chdir: "/opt/cloned-repos/monasca-agent"
  register: agent_result
  changed_when: "agent_result.rc == 0"
  tags:
    - monasca-agent-tarball
    - monasca-install-agent

- name: Get tarball file name
  shell: "ls -td /opt/cloned-repos/monasca-agent/dist/monasca-agent-*.tar.gz | head -1"
  register: tarball
  changed_when: false
  tags:
    - monasca-install-agent

- name: Install monasca-agent
  pip:
    name: "file://{{ tarball.stdout }}"
    virtualenv: "/opt/venvs/monasca-agent"
  tags:
    - monasca-install-agent

- name: Drop monasca-agent config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "host_alive.yaml.j2"
      dest: "/etc/monasca/agent/conf.d/host_alive.yaml"
      owner: "root"
      group: "root"
      mode: "0644"
    - src: "monasca-reconfigure.j2"
      dest: "/usr/local/bin/monasca-reconfigure"
      owner: "root"
      group: "root"
      mode: "0750"
  notify:
    - Restart monasca-agent
  tags:
    - monasca-agent-config
    - monasca-install-agent

- name: Drop required plugin(s) config(s) on /root
  template:
    src: "{{ item }}.j2"
    dest: "/root/.{{ item }}"
  with_items:
    - "my.cnf"
    - "apache.cnf"
    - "supervisord.cnf"
#  when: "inventory_hostname in groups['devstack']"
  tags:
    - monasca-plugins
    - monasca-install-agent

- name: Run monasca-reconfigure
  command: "/usr/local/bin/monasca-reconfigure"
  register: reconfigure_result
  changed_when: "reconfigure_result.rc == 0"
  ignore_errors: true
  notify:
    - Restart monasca-agent
  tags:
    - monasca-agent-reconfigure
    - monasca-install-agent
