---
# Copyright 2016 LSD/UFCG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Copy 'docker.yaml' file
  copy:
    dest: /etc/monasca/agent/conf.d/docker.yaml
    src: docker.yaml
    mode: 0755

- name: Copy 'docker.py' file
  copy:
    dest: /opt/venvs/monasca-agent/lib/python2.7/site-packages/monasca_agent/collector/checks_d/docker.py
    src: docker.py
    mode: 0755

- name: Modify /run/docker permission files
  file:
    path: /run/docker
    mode: "u+rx,g+rx,o+rx"

- name: Add 'mon-agent' user to docker group
  user:
    name: mon-agent
    groups: docker
  notify:
    - Restart docker

- name: Install pip docker package in 'monasca-agent' venv
  pip:
    name: docker
    virtualenv: "/opt/venvs/monasca-agent"
  notify:
    - Restart monasca-agent
